import {
  IBlog,
  IDoctor,
  IEvent,
  IPatientReview,
  IProduct,
  IRecordService,
} from "@/types/types";

export const dentists: IDoctor[] = [
  {
    image: "doctors/dentist1.jpg",
    name: "Dr. John Doe",
    title: "Orthodontist",
    experience: "10+ yr. of practice",
    workTime: "Mon-Fri, 9am - 5pm",
    phone: "+1 555 123 4567",
    reviews: "4.9/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Top Rated",
    location: "Green Valley",
  },
  {
    image: "doctors/dentist2.jpg",
    name: "Dr. Jane Smith",
    title: "Pediatric Dentist",
    experience: "8+ yr. of practice",
    workTime: "Mon-Fri, 8am - 4pm",
    phone: "+1 555 234 5678",
    reviews: "4.8/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Family-Friendly",
    location: "River Park",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Dr. Emily Davis",
    title: "Endodontist",
    experience: "12+ yr. of practice",
    workTime: "Tue-Sat, 10am - 6pm",
    phone: "+1 555 345 6789",
    reviews: "5.0/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Expert",
    location: "Lakewood Heights",
  },
  {
    image: "doctors/dentist4.jpg",
    name: "Dr. Michael Brown",
    title: "Periodontist",
    experience: "15+ yr. of practice",
    workTime: "Mon-Thu, 9am - 4pm",
    phone: "+1 555 456 7890",
    reviews: "4.7/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Experienced",
    location: "Sunset Hills",
  },
  {
    image: "doctors/dentist1.jpg",
    name: "Dr. Sarah Wilson",
    title: "Prosthodontist",
    experience: "7+ yr. of practice",
    workTime: "Mon-Fri, 10am - 5pm",
    phone: "+1 555 567 8901",
    reviews: "4.6/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Most Popular",
    location: "Maple Grove",
  },
  {
    image: "doctors/dentist2.jpg",
    name: "Dr. David Johnson",
    title: "General Dentist",
    experience: "9+ yr. of practice",
    workTime: "Mon-Fri, 9am - 5pm",
    phone: "+1 555 678 9012",
    reviews: "4.8/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Highly Recommended",
    location: "Hillcrest Village",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Dr. Laura Martinez",
    title: "Oral Surgeon",
    experience: "14+ yr. of practice",
    workTime: "Mon-Wed, 9am - 4pm",
    phone: "+1 555 789 0123",
    reviews: "4.9/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Award-Winning",
    location: "Oakwood Estates",
  },
  {
    image: "doctors/dentist4.jpg",
    name: "Dr. Robert Garcia",
    title: "Cosmetic Dentist",
    experience: "6+ yr. of practice",
    workTime: "Tue-Sat, 10am - 6pm",
    phone: "+1 555 890 1234",
    reviews: "4.7/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "New Patients",
    location: "Cedar Springs",
  },
  {
    image: "doctors/dentist1.jpg",
    name: "Dr. Anna Lee",
    title: "Oral Pathologist",
    experience: "11+ yr. of practice",
    workTime: "Mon-Fri, 9am - 5pm",
    phone: "+1 555 901 2345",
    reviews: "4.9/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Expert",
    location: "Forest Ridge",
  },
  {
    image: "doctors/dentist2.jpg",
    name: "Dr. James Miller",
    title: "General Dentist",
    experience: "13+ yr. of practice",
    workTime: "Mon-Fri, 8am - 4pm",
    phone: "+1 555 012 3456",
    reviews: "4.8/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Emergency Services",
    location: "Springfield Acres",
  },
  {
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    name: "Dr. John Smith",
    title: "General Dentist",
    experience: "10 yr. of practice",
    workTime: "Mon-Fri, 9 AM - 5 PM",
    phone: "(123) 456-7890",
    reviews: "4.8/5 (120 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Expert",
    location: "Silver Lake",
  },
  {
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    name: "Dr. Emily Johnson",
    title: "Pediatric Dentist",
    experience: "8 yr. of practice",
    workTime: "Mon-Sat, 10 AM - 4 PM",
    phone: "(234) 567-8901",
    reviews: "4.9/5 (140 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "New Patients",
    location: "Shady Oaks",
  },
  {
    image: "https://randomuser.me/api/portraits/men/55.jpg",
    name: "Dr. Michael Lee",
    title: "Orthodontist",
    experience: "12 yr. of practice",
    workTime: "Tue-Sat, 9 AM - 6 PM",
    phone: "(345) 678-9012",
    reviews: "4.7/5 (110 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Award-Winning",
    location: "Pine Ridge",
  },
  {
    image: "https://randomuser.me/api/portraits/women/54.jpg",
    name: "Dr. Sarah Williams",
    title: "Cosmetic Dentist",
    experience: "15 yr. of practice",
    workTime: "Mon-Fri, 8 AM - 4 PM",
    phone: "(456) 789-0123",
    reviews: "4.8/5 (200 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Highly Recommended",
    location: "Willow Springs",
  },
  {
    image: "https://randomuser.me/api/portraits/men/72.jpg",
    name: "Dr. David Brown",
    title: "Periodontist",
    experience: "20 yr. of practice",
    workTime: "Mon-Thu, 10 AM - 5 PM",
    phone: "(567) 890-1234",
    reviews: "4.9/5 (95 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Most Popular",
    location: "Fairview Gardens",
  },
  {
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    name: "Dr. Olivia Davis",
    title: "Endodontist",
    experience: "11 yr. of practice",
    workTime: "Wed-Sun, 9 AM - 3 PM",
    phone: "(678) 901-2345",
    reviews: "4.7/5 (130 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Experienced",
    location: "Glenwood Heights",
  },
  {
    image: "https://randomuser.me/api/portraits/men/41.jpg",
    name: "Dr. William Martinez",
    title: "Prosthodontist",
    experience: "18 yr. of practice",
    workTime: "Mon-Fri, 7 AM - 3 PM",
    phone: "(789) 012-3456",
    reviews: "4.9/5 (160 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Expert",
    location: "Riverstone Park",
  },
  {
    image: "https://randomuser.me/api/portraits/women/36.jpg",
    name: "Dr. Sophia Hernandez",
    title: "Oral Surgeon",
    experience: "9 yr. of practice",
    workTime: "Tue-Sat, 11 AM - 7 PM",
    phone: "(890) 123-4567",
    reviews: "4.8/5 (180 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Top Rated",
    location: "Maplewood Ridge",
  },
  {
    image: "https://randomuser.me/api/portraits/men/66.jpg",
    name: "Dr. James Anderson",
    title: "General Dentist",
    experience: "14 yr. of practice",
    workTime: "Mon-Fri, 9 AM - 6 PM",
    phone: "(901) 234-5678",
    reviews: "4.7/5 (175 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Highly Recommended",
    location: "Mountain View",
  },
  {
    image: "https://randomuser.me/api/portraits/women/43.jpg",
    name: "Dr. Ava Thomas",
    title: "Pediatric Dentist",
    experience: "7 yr. of practice",
    workTime: "Mon-Fri, 8 AM - 5 PM",
    phone: "(012) 345-6789",
    reviews: "4.9/5 (190 reviews)",
    viewProfileLink: "#",
    appointmentLink: "#",
    badge: "Family-Friendly",
    location: "Cypress Meadows",
  },
];

export const dentistEvents: IEvent[] = [
  {
    title: "Advanced Dental Implants Workshop",
    description:
      "A comprehensive workshop on the latest techniques in dental implants.",
    category: "Workshop",
    date: "Mar 4",
    location: "New York, NY",
    image:
      "https://adanews.ada.org/media/si2l20xu/attendees.jpg?rmode=max&width=500",
    speaker: "Dr. Emily Turner",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Pediatric Dentistry Seminar",
    description:
      "Learn the best practices for treating dental issues in children.",
    category: "Seminar",
    date: "Mar 14",
    location: "San Francisco, CA",
    image:
      "https://adanews.ada.org/media/0tabj22q/markarian.jpg?rmode=max&width=500",
    speaker: "Dr. Michael Robertson",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Advanced Dental Implants Workshop",
    description:
      "A comprehensive workshop on the latest techniques in dental implants.",
    category: "Workshop",
    date: "Mar 4",
    location: "New York, NY",
    image:
      "https://adanews.ada.org/media/si2l20xu/attendees.jpg?rmode=max&width=500",
    speaker: "Dr. Emily Turner",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Orthodontics Conference 2024",
    description:
      "A conference covering the latest advancements in orthodontics.",
    category: "Conference",
    date: "Oct 2",
    location: "Chicago, IL",
    image:
      "https://blogs.dentalkart.com/wp-content/uploads/2023/10/DENTAL-CONFERENCE-800x401.png",
    speaker: "Dr. Sarah Collins",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Dental Hygiene Symposium",
    description: "Explore the latest trends and techniques in dental hygiene.",
    category: "Symposium",
    date: "Oct 3",
    location: "Los Angeles, CA",
    image:
      "https://assets.speareducation.com/digest/2023/12/why-dental-workshops-work-the-crucial-role-in-continuing-education/7905-Digest-Dental-Workshop-Fig1.jpg",
    speaker: "Dr. Kevin Walker",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Orthodontics Conference 2024",
    description:
      "A conference covering the latest advancements in orthodontics.",
    category: "Conference",
    date: "Oct 2",
    location: "Chicago, IL",
    image:
      "https://blogs.dentalkart.com/wp-content/uploads/2023/10/DENTAL-CONFERENCE-800x401.png",
    speaker: "Dr. Sarah Collins",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Cosmetic Dentistry Expo",
    description: "An expo showcasing innovations in cosmetic dentistry.",
    category: "Expo",
    date: "Oct 5",
    location: "Miami, FL",
    image:
      "https://assets.speareducation.com/digest/2023/12/why-dental-workshops-work-the-crucial-role-in-continuing-education/7905-Digest-Dental-Workshop-Fig2.jpg",
    speaker: "Dr. Olivia James",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Endodontics Techniques Masterclass",
    description: "Masterclass on advanced endodontic techniques.",
    category: "Masterclass",
    date: "Oct 7",
    location: "Boston, MA",
    image:
      "https://assets.speareducation.com/digest/2023/12/why-dental-workshops-work-the-crucial-role-in-continuing-education/7905-Digest-Dental-Workshop-Fig3.jpg",
    speaker: "Dr. Daniel Smith",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Cosmetic Dentistry Expo",
    description: "An expo showcasing innovations in cosmetic dentistry.",
    category: "Expo",
    date: "Oct 5",
    location: "Miami, FL",
    image:
      "https://assets.speareducation.com/digest/2023/12/why-dental-workshops-work-the-crucial-role-in-continuing-education/7905-Digest-Dental-Workshop-Fig2.jpg",
    speaker: "Dr. Olivia James",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Dental Practice Management Workshop",
    description: "Improve your dental practice management skills.",
    category: "Workshop",
    date: "Oct 20",
    location: "Dallas, TX",
    image:
      "https://www.miramarpd.org/ImageRepository/Document?documentID=29821",
    speaker: "Dr. Laura Harris",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Oral Surgery Innovations Seminar",
    description: "Seminar on the latest innovations in oral surgery.",
    category: "Seminar",
    date: "Nov 5",
    location: "Seattle, WA",
    image:
      "https://assets.speareducation.com/digest/2023/12/why-dental-workshops-work-the-crucial-role-in-continuing-education/7905-Digest-Dental-Workshop-Fig3.jpg",
    speaker: "Dr. Chris Martinez",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Dental Practice Management Workshop",
    description: "Improve your dental practice management skills.",
    category: "Workshop",
    date: "Oct 20",
    location: "Dallas, TX",
    image:
      "https://www.miramarpd.org/ImageRepository/Document?documentID=29821",
    speaker: "Dr. Laura Harris",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Digital Dentistry Symposium",
    description: "Explore the future of digital technology in dentistry.",
    category: "Symposium",
    date: "Nov 15",
    location: "Austin, TX",
    image:
      "https://assets.speareducation.com/digest/2023/12/why-dental-workshops-work-the-crucial-role-in-continuing-education/7905-Digest-Dental-Workshop-Fig2.jpg",
    speaker: "Dr. Jessica Wilson",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Dental Practice Management Workshop",
    description: "Improve your dental practice management skills.",
    category: "Workshop",
    date: "Oct 20",
    location: "Dallas, TX",
    image:
      "https://www.miramarpd.org/ImageRepository/Document?documentID=29821",
    speaker: "Dr. Laura Harris",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Holistic Dentistry Conference",
    description: "A conference on holistic approaches to dental care.",
    category: "Conference",
    date: "Nov 22",
    location: "Denver, CO",
    image:
      "https://www.miramarpd.org/ImageRepository/Document?documentID=29821",
    speaker: "Dr. Benjamin Clark",
    time: "2:20 AM - 4:20 AM",
  },
  {
    title: "Dental Practice Management Workshop",
    description: "Improve your dental practice management skills.",
    category: "Workshop",
    date: "Oct 20",
    location: "Dallas, TX",
    image:
      "https://www.miramarpd.org/ImageRepository/Document?documentID=29821",
    speaker: "Dr. Laura Harris",
    time: "2:20 AM - 4:20 AM",
  },
];

export const products: IProduct[] = [
  {
    images: ["./tools/tool1.png", "./tools/tool2.png", "./tools/tool3.png"],
    name: "Cosmetic Dentistry",
    description: `Cosmetic dentistry involves a variety of professional treatments aimed at improving the appearance of teeth. Crowns, dental implants, teeth whitening, and veneers are the most popular cosmetic dental procedures.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Dental Tools & Accessories",
  },
  {
    images: ["./tools/tool6.png", "./tools/tool5.png", "./tools/tool4.png"],
    name: "Cosmetic Dentistry",
    description: `Cosmetic dentistry involves a variety of professional treatments aimed at improving the appearance of teeth. Crowns, dental implants, teeth whitening, and veneers are the most popular cosmetic dental procedures.`,
    star: 5,
    productVideo: "carVideo1.mp4",
    buttonText: "Know More",
    category: "Dental Tools & Accessories",
  },
  {
    images: ["./tools/tool4.png", "./tools/tool5.png", "./tools/tool6.png"],
    name: "Microscopic Dentistry",
    description: `Microscopic Dentistry enables a dentist to perform precise and accurate dental procedures. The human eye has a resolution of only 0.2 millimetres when it is unaided.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Dental Tools & Accessories",
  },
  {
    images: ["./tools/tool1.png", "./tools/tool2.png", "./tools/tool3.png"],
    name: "Dental Implants",
    description: `A dental implant is a solution to your pain and grief if missing teeth are preventing you from enjoying your favourite foods and affecting your self-esteem.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Ceramic Dental Implants",
  },
  {
    images: ["./tools/tool6.png", "./tools/tool4.png", "./tools/tool5.png"],
    name: "Dental Implants",
    description: `A dental implant is a solution to your pain and grief if missing teeth are preventing you from enjoying your favourite foods and affecting your self-esteem.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Ceramic Dental Implants",
  },
  {
    images: ["./tools/tool1.png", "./tools/tool2.png", "./tools/tool3.png"],
    name: "Dental Implants",
    description: `A dental implant is a solution to your pain and grief if missing teeth are preventing you from enjoying your favourite foods and affecting your self-esteem.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Ceramic Dental Implants",
  },
  {
    images: ["./tools/tool1.png", "./tools/tool2.png", "./tools/tool3.png"],
    name: "Dental Implants",
    description: `A dental implant is a solution to your pain and grief if missing teeth are preventing you from enjoying your favourite foods and affecting your self-esteem.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Clinic Experiences",
  },
  {
    images: ["./tools/tool6.png", "./tools/tool5.png", "./tools/tool4.png"],
    name: "Dental Implants",
    description: `A dental implant is a solution to your pain and grief if missing teeth are preventing you from enjoying your favourite foods and affecting your self-esteem.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Clinic Experiences",
  },
  {
    images: ["./tools/tool3.png", "./tools/tool1.png", "./tools/tool2.png"],
    name: "Dental Implants",
    description: `A dental implant is a solution to your pain and grief if missing teeth are preventing you from enjoying your favourite foods and affecting your self-esteem.`,
    star: 5,
    buttonText: "Know More",
    productVideo: "carVideo1.mp4",
    category: "Clinic Experiences",
  },
];

export const blogs: IBlog[] = [
  {
    title: "Top 5 Tips for Maintaining Oral Hygiene",
    description:
      "Discover the best practices for keeping your teeth and gums healthy with these expert tips. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "4 Sep",
    category: "Dental Service",
    image:
      "https://www.pharmaadda.in/wp-content/uploads/2019/06/Dental-Products-List-2.jpg",
    publisher: {
      name: "Dr. Emily Carter",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "Understanding Dental Implants: A Comprehensive Guide",
    description:
      "Everything you need to know about dental implants, from the procedure to aftercare. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "8 Sep",
    category: "Dental Service",
    image:
      "https://media.licdn.com/dms/image/C5612AQEgs75Jpajzww/article-cover_image-shrink_600_2000/0/1607034426222?e=2147483647&v=beta&t=3UiGOIJwg5dg-inw2JF9GUCjmjwRFkFaQZ06Y2dby_0",
    publisher: {
      name: "Dr. Robert Allen",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "The Best Toothpaste for Sensitive Teeth in 2024",
    description:
      "Explore the top toothpaste options for those with sensitive teeth, reviewed by dentists. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "2 Sep",
    category: "Dental Product",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-EKxUdJoBe34XF0Tw3yofiff9ktmsG0JhpA&s",
    publisher: {
      name: "Dr. Sarah Johnson",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "Why Regular Dental Checkups are Essential for Your Health",
    description:
      "Learn why visiting your dentist regularly is crucial for preventing serious dental issues. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "7 Sep",
    category: "Dental Service",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC1gBEbqfJIsqERwXnaKsT8-TePktExdtcZ0hrAZV8evZlUURVzvJoK6gac-qvIPrVPz4&usqp=CAU",
    publisher: {
      name: "Dr. Michael Brown",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "The Latest Advancements in Cosmetic Dentistry",
    description:
      "A look into the newest technologies and treatments in cosmetic dentistry. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "5 Sep",
    category: "Dentist Medicine",
    image:
      "https://www.pharmaadda.in/wp-content/uploads/2019/06/Dental-Products-List-2.jpg",
    publisher: {
      name: "Dr. Lisa Williams",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "How to Choose the Right Mouthwash for Your Oral Health",
    description:
      "A guide to selecting the best mouthwash based on your specific dental needs. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "3 Sep",
    category: "Dental Product",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc6yjoEZwF2wamCqgLpDynGsYRsMg2dP-wSg&s",
    publisher: {
      name: "Dr. Kevin Davis",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "Top 10 Foods That Are Good for Your Teeth",
    description:
      "A list of foods that promote healthy teeth and gums, recommended by dental experts. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "9 Sep",
    category: "Dentist Medicine",
    image:
      "https://www.lightbreezedental.com/wp-content/uploads/mini-dental-implants20166.jpg",
    publisher: {
      name: "Dr. Emma Green",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "The Benefits of Professional Teeth Whitening",
    description:
      "Explore the advantages of getting your teeth whitened by a professional dentist. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "6 Sep",
    category: "Dental Service",
    image:
      "https://www.pedroarteche.com/wp-content/uploads/2019/01/What-are.jpg",
    publisher: {
      name: "Dr. John Smith",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "Dental Care for Kids: Tips and Tricks",
    description:
      "Helpful advice for parents to ensure their children maintain excellent dental health. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "1 Sep",
    category: "Dental Service",
    image:
      "https://www.henryschein.com/us-en/images/dental/dental-supplies-2019-cat-2.jpg",
    publisher: {
      name: "Dr. Megan White",
      image: "doctors/dentist3.jpg",
    },
  },
  {
    title: "How to Prevent and Treat Gum Disease",
    description:
      "An in-depth guide to understanding, preventing, and managing gum disease. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta eum expedita veritatis esse culpa, deserunt, animi non facilis necessitatibus minus aspernatur! Rem temporibus maiores nemo quo sed, vitae nulla deleniti minima nesciunt labore incidunt illo a quia, et dicta consequuntur.",
    publishData: "7 Sep",
    category: "Dentist Medicine",
    image:
      "https://media.licdn.com/dms/image/C5612AQEgs75Jpajzww/article-cover_image-shrink_600_2000/0/1607034426222?e=2147483647&v=beta&t=3UiGOIJwg5dg-inw2JF9GUCjmjwRFkFaQZ06Y2dby_0",
    publisher: {
      name: "Dr. David Thompson",
      image: "doctors/dentist3.jpg",
    },
  },
];

export const recordService: IRecordService[] = [
  {
    numberOfAmount: "96%",
    title: "Positive Feedback",
    subTitle: "from our patients",
  },
  {
    numberOfAmount: "3126",
    title: "Patient Recover",
    subTitle: "from our doctors",
  },
  {
    numberOfAmount: "16",
    title: "Years Experience",
    subTitle: "of medical emergencies",
  },
  {
    numberOfAmount: "12",
    title: "Surgery Room",
    subTitle: "from our clinics",
  },
];

export const patientReviews: IPatientReview[] = [
  {
    image: "doctors/dentist3.jpg",
    name: "John Doe",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 5,
    description:
      "Amazing service! The dentist was very professional and made me feel at ease throughout the procedure. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia. ",
    platform: "Google",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Jane Smith",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 4,
    description:
      "Great experience overall, but the waiting time was a bit long. The staff was very friendly though. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Facebook",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Michael Johnson",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 5,
    description:
      "Best dental clinic I've ever been to. The staff is kind, and the equipment is top-notch! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Yelp",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Emily Davis",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 4,
    description:
      "Very good experience! The dentist explained everything thoroughly and the results were great. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Google",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Chris Lee",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 5,
    description:
      "I was nervous at first, but the dentist and staff made me feel very comfortable. Highly recommend! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Google",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Sophia Martinez",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 4,
    description:
      "The service was great, but I felt the procedure was a bit rushed. Overall, still a great clinic. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Facebook",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Liam Brown",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 5,
    description:
      "Excellent experience. My teeth have never felt better, and the follow-up care was great too. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Google",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Olivia Wilson",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 4,
    description:
      "Lovely staff, very professional and caring. Would recommend this clinic to anyone! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Yelp",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Noah Anderson",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 5,
    description:
      "Fantastic service! The dentist made sure I was comfortable the entire time. Will definitely come back. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Google",
  },
  {
    image: "doctors/dentist3.jpg",
    name: "Isabella Garcia",
    date: "September 4, 2024 at 8:22 AM GMT+6",
    star: 5,
    description:
      "Great experience! The team was friendly and knowledgeable. The results were better than I expected. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente laboriosam accusamus iste. Debitis ipsum sit assumenda, consectetur, exercitationem sint eius autem molestiae, sed saepe natus voluptas placeat iusto quibusdam officia.",
    platform: "Facebook",
  },
];
